### ISSUE TITLE
是否采用繁体更好？

### ISSUE THREAD

**Issue by chianjin** [lingr7/HongLouMeng-ZhiPingBen#1]
底本是简体版吗？我以为整理古籍最好还是繁体为好。

**Comment by lingr7** [comment]
这个版本是和亚马逊电子书商店卖的的红楼梦脂评汇校本一致，那个正文就是简体的。另外关于生僻字，现有几十个生僻字都是用图片的形式插入的，应该都能正常显示的。

**Comment by lingr7** [comment]
去查了一下发现这个本子也有繁体竖排的版本。https://www.amazon.cn/dp/B00MUQULMY/ref=emc_b_5_i

**Comment by lingr7** [comment]
考虑到面向的读者，还是采用简体，比如我就是看这本才读完了红楼梦的80回。
