### ISSUE TITLE
批注标识重新实现和部分生僻字支持

### ISSUE THREAD

**Issue by chianjin** [lingr7/HongLouMeng-ZhiPingBen#2]
批注标志无需插入图，用 tikz 实现。另外支持生僻字的调用，但仍有两个生僻字没有找到。
实例代码如下。可以试试。

`\documentclass[zihao=5]{ctexart}

\usepackage{tikz}
\usepackage{expl3}
\usepackage{ifthen}

% 扩展字符字体，找到了：𥁐𢔤𢓯𣬠𣬶𦵾𣢑𠟜𤏰𥿮𤫫𥁢𠳐
\xeCJKsetup{AutoFallBack=true}
\setCJKfallbackfamilyfont{\CJKrmdefault}{SimSun-ExtB}
% 几何图形，方块，菱形等
\xeCJKsetcharclass{"2500}{"25FF}{1}  %

% 定义字符边框
\newcommand{\noteflag}[4]{%
    \raisebox{-0.2em}[0.0ex][0.0ex]{%
        \begin{tikzpicture}
            \node[rectangle,fill=#1,draw=#2,rounded corners=0.05em,inner sep=0.05em,minimum size=1.05em] at (0,0){\kaishu\color{#3}#4};
        \end{tikzpicture}
    }%
}

% 定义注释命令
% \snote{甲}{...}
% \snote{蒙}[侧]{...}
% TODO： 
%   注释内容不能分段，需要解决。目前采用硬换行后设置缩进，例如：
%   故曰“贾雨村”云云。\\\\
%   \indent
%   此回中凡用“梦”用“幻”等字
\NewDocumentCommand{\snote}{mom}{%
    \hspace{0.05em}\ifthenelse{\equal{#1}{甲}}
    {\noteflag{red}{red}{white}{#1}}
    {\noteflag{black}{black}{white}{#1}}%
    \IfNoValueTF{#2}
    {\hspace{-0.35em}{\kaishu #3}\hspace{-0.35em}}
    {\hspace{-0.3em}\noteflag{none}{black}{black}{#2}\hspace{-0.3em}{\kaishu\small #3}\hspace{-0.35em}}
}

\begin{document}
𥁐𢔤𢓯𣬠𣬶𦵾𣢑𠟜𤏰𥿮𤫫𥁢𠳐
    
\snote{庚}{此开卷第一回也。作者自云：因曾历过一番梦幻之后，故将真事隐去，而借通灵之说，撰
此《石头记》一书也，故曰“甄士隐”云云。但书中所记何事何人？自又云：“今风尘碌碌，一事
无成，忽念及当日所有之女子，一一细考较去，觉其行止见识皆出于我之上。何我堂堂须眉，诚
不若此裙钗哉？\snote{蒙}[侧]{何非梦幻，何不通灵？作者托言，原当有自。受气清浊，本无男女之别。}实愧则有馀，悔又
无益之大无可如何之日也！当此，则自欲将已往所赖天恩祖德，锦衣纨绔之时，饫甘餍肥之日，
背父兄教育之恩，负师友规谈之德，以至今日一技无成、半生潦倒之罪，\snote{蒙}[侧]{明告看者。}编述一集，
以告天下人：我之罪固不免，然闺阁中本自历历有人，万不可因我之不肖，自护己短，一并使其
泯灭也。\snote{蒙}[侧]{因为传他，并可传我。}虽今日之茅椽蓬牖，瓦灶绳床，其晨夕风露，阶柳庭花，亦未有
妨我之襟怀笔墨。虽我未学，下笔无文，又何妨用假语村言敷演出一段故事来？亦可使闺阁昭传，
复可悦世之目，破人愁闷，不亦宜乎？”故曰“贾雨村”云云。\\\\
\indent
此回中凡用“梦”用“幻”等字，是提醒阅者眼目，亦是此书立意本旨。}列位看官，你道
此书从何而来？说起根由虽近荒唐，\snote{甲}[侧]{自占地步。◇自首荒唐，妙！}细谙则深有趣味。待在下将此来
历注明，方使阅者了然不惑。

原来，女娲氏炼石补天之时，\snote{甲}[侧]{补天济世，勿认真用常言。}于大荒山甲侧荒唐也。无稽崖\snote{甲}[侧]{无稽
也。}炼成高经十二丈、\snote{甲}[侧]{总应十二钗。}方经二十四丈\snote{甲}[侧]{照应副十二钗。}顽石三万六千五百零一块。娲
皇氏只用了三万六千五百块，\snote{甲}[侧]{合周天之数。}\snote{蒙}[侧]{数足，偏遗我。“不堪入选”句中透出心眼。}只单单的
剩了一块未用，\snote{甲}[侧]{剩了这一块便生出这许多故事。使当日虽不以此补天，就该去补地之坑陷，使地平坦，而不得
有此一部鬼话。}便弃在此山青埂峰下。\snote{甲}[眉]{妙！自谓落堕情根，故无补天之用。}谁知此石自经煅炼之后，灵
性已通，\snote{甲}[侧]{煅炼后性方通。甚哉，人生不能学也！}因见众石俱得补天，独自己无材不堪入选，遂自怨自
叹，日夜悲号惭愧。
\end{document}`

**Comment by chianjin** [comment]
\RequirePackage{tikz}
\RequirePackage{ifthen}
\RequirePackage{xparse}
\NewDocumentCommand{\snote}{mom}{%
    \raisebox{-0.2em}{%
        \begin{tikzpicture}
            \ifthenelse{\equal{#1}{甲}}
                {\node[draw=red,fill=red,inner sep=0pt,minimum size=1.05em,rounded corners=0.1em] at (0,0) {\color{white}\kaishu 甲};}
                {\node[draw,fill=black,inner sep=0pt,minimum size=1.05em,rounded corners=0.1em] at (0,0) {\color{white}\kaishu #1};}
            \IfNoValueF{#2}
                {\node[draw,inner sep=0pt,minimum size=1.05em,rounded corners=0.1em] at (1.1em,0) {{\kaishu #2}};}
        \end{tikzpicture}%
    }{{\IfNoValueF{#2}{\small}\kaishu #3}}%
}

重新实现注释标记

**Comment by lingr7** [comment]
首先要感谢你找到了一些生僻字，全文涉及到的生僻字，我在2021年7月集中寻找过一次都找到了Utf8编码，想要替换掉图片的实现，但是考虑到编译环境字体各异，字体支持的有限情况，有些即使不算很生僻的字甚至就是常见字，在更换字体后依然无法正确渲染，所以保留了图片插入的实现。

**Comment by lingr7** [comment]
现在没有编译环境，等有编译环境了，测试并使用你提供的代码。

**Comment by lingr7** [comment]
snote的方案采用了。暂时还未提交，因为要恢复插入图片的生僻字实现方案
关于生僻字的处理，不可避免地要考虑到字体的问题，经过我的多方尝试，寻找到了很多字体，比如说猫啃网上的很多字体，阿里妈妈大楷，比如说，花园体，各种ttf,ttc下载一通，后来才发现微软雅黑，微软正黑体，win10 win11自带的字体才是覆盖面最广的字体（绕了一圈，回到原点），还是保留原来这几个生僻字的实现。包括能够在github网站上显示的这些字体，就是微软雅黑，微软正黑。

**Comment by lingr7** [comment]
查看使用到的字体的方法。使用浏览器F12![image](https://github.com/lingr7/HongLouMeng-ZhiPingBen/assets/37898999/65a23541-90cf-4c17-acf6-97d1af98ea33)
